#!/usr/bin/env bash
# this bash script creat a file "/var/run/myscript.pid containing its PID"

My_pid=$$
file="/var/run/myscript.pid"
echo "$My_pid" > "$file"

cleanup()
{
	rm "$file"
	exit
}

trap 'cleanup' SIGQUIT SIGTERM

ignore_sigterm()
{
	echo "I hate the kill command"
	exit
}

trap 'ignore_sigterm' SIGTERM

ignore_sigint()
{
	echo "Y U no love me?!"
}

trap 'ignore_sigint' SIGINT

while true
do
	echo "To infinity and beyond"
	sleep 2
done
