#!/usr/bin/env bash
# Read and process /etc/passwd using while loop and IFS

while IFS=: read -r username password uid gid gecos home shell; do
    # Extract user ID information from gecos field
    user_info=$(echo "$gecos" | awk -F',' '{print $5}')
    
    # Display user information
    echo "The user $username is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode $password, more info about the user here: $user_info"
done < /etc/passwd

